name: 'Shamshir'
description: 'Labeling'
author: 'Your name'

inputs:
  GITHUB_TOKEN:
    description: 'GitHub token'
    required: true
  owner:
    description: 'Github repository owner'
    required: true
  repo:
    description: 'Github repository'
    required: true
  label:
    description: 'Github label'
    required: true
  quorum:
    description: 'The quorum of approval'
    required: true

outputs:
  log:
    description: 'shamshir-run log message for github actions'

runs:
  using: 'node16'
  main: 'dist/index.js'