name: 'Thank You Action'
description: 'Say "Thank You" to new pull requests'
author: 'Kazuo Yagi'

inputs:
  GITHUB_TOKEN:
    description: 'GitHub token'
    required: true
  owner:
    description: 'owner'
    required: true
  repo:
    description: 'repo'
    required: true
  label:
    description: 'label'
    required: true
  quorum:
    description: 'quorum'
    required: true

outputs:
  log:
    description: 'log'

runs:
  using: 'node16'
  main: 'dist/index.js'