name: 'Thank You Action'
description: 'Say "Thank You" to new pull requests'
author: 'Kazuo Yagi'

inputs:
  GITHUB_TOKEN:
    description: 'GitHub token'
    required: true

outputs:
  log:
    description: 'log'

runs:
  using: 'node16'
  main: 'dist/index.js'