name: Releasable label manager
on: [ pull_request_target ]

permissions:
  contents: read
  pull-requests: write

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: './.github/actions/releasable-label-manager'
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
