name: Shamshir
on:
  pull_request_review:
    types: [submitted, edited, dismissed]
  pull_request:
    types: [edited, labeld, unlabeled]
jobs:
  Labeling-Agent:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🌙 Shamshir was automatically triggered by a ${{ github.event_name }} event."
      - uses: actions/checkout@v2
      - run: npm install
      - id: 1
        uses: ./
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          owner: ${{ github.repository_owner }}
          repo:  ${{ github.repository }}
          label: 'releasable'
          quorum: '1'
      - run: echo "${{ steps.1.outputs.log }}"
      - run: echo "🌙 Shamshir's status is ${{ job.status }}."
