name: Shamshir

on:
  pull_request_review:
    types: [submitted, edited, dismissed]
  pull_request:
    types: [edited, labeld, unlabeled]

jobs:
  shamshir:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - run: npm install
    - run: echo ::set-env name=REPOSITORY_NAME::$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}')
      shell: bash
    - uses: ./dist/index.js --owner ${{GITHUB_REPOSITORY_OWNER}} --repo ${{REPOSITORY_NAME}} --label releasable --quorum 1
      with:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}